data:
  # folder: folder containing test set of images. Must be an absolute path, with no nested folders inside.
  folder: C:\Users\pensf\Documents\AutomatedLBP_Benchmarking\LBP_Test_Images\RotatedTexturePatches_NoBorder

rng:
  seed: 42

local_binary_patterns:
  P: 8
  R: 1.0
  method: "ror"   # [default, ror, uniform, var, ltp]
  use_ltp: true   # if true, uses Local Ternary Patterns instead of LBP
  ltp:
    threshold: 5     # enables LTP if set
    use_image_mask: false   # if true, uses a mask of valid pixels for LTP (e.g. to avoid borders)

matching:
  metric: "chi2"      # [chi2, cosine, hellinger]
  tolerance: null
  top: 5

preprocessing:
  gaussian_blur: 0.0
  gaussian_noise: 10
  illumination: null
  contrast: null

data_engineering:
  histogram_smoothing: 0.000001

cropping:
  width: null         # X
  height: null        # Y
  random_crop: false

output:
  save_csv: "matches.csv"      # or "matches.csv"
  visualize: false

logging:
  verbose: false