data:
  # folder: folder containing test set of images. Must be an absolute path, with no nested folders inside.
  folder: LBP_Test_Images\RotatedTexturePatches_NoBorder

rng:
  seed: 42

local_binary_patterns:
  P: 8
  R: 1.0
  method: "uniform"   # [default, ror, uniform, var, ltp] IF use_ltp is false. Otherwise, [ror, uniform]
  use_ltp: false   # if true, uses Local Ternary Patterns instead of LBP
  ltp:
    threshold: 5     # threshold for generating LTP codes (during neighbor coparison, differences in threshold will be encoded as 0)
    use_image_mask: false   # if true, uses a mask of valid pixels for LTP (e.g. to avoid borders)

matching:
  metric: "chi2"      # [chi2, cosine, hellinger]
  tolerance: 1     # tolerance for matching histograms. Matches will only be reported if distance is below this threshold. Set to 1 to allow all matches.
  top: 5          # Number of matches to report per image. Tolerance takes precedence.

preprocessing:
  gaussian_blur: null
  gaussian_noise: null
  illumination: null
  contrast: null

data_engineering:
  histogram_smoothing: null

cropping:
  width: 256
  height: 256
  random_crop: false

output:
  csv_filename: "auto"  # File name for csv. If auto, generates a descriptive name from config.
  pdf_filename: "matches"
  visualize: true

logging:
  verbose: false