data:
  # folder: folder containing test set of images. Must be an absolute path, with no nested folders inside.
  folder: LBP_Test_Images\RotatedTexturePatches_NoBorder

rng:
  seed: 42

local_binary_patterns:
  P: 8
  R: 1.0
  method: "ror"   # [default, ror, uniform, var, ltp] IF use_ltp is false. Otherwise, [ror, uniform]
  use_ltp: false   # if true, uses Local Ternary Patterns instead of LBP
  ltp:
    threshold: 5     # threshold for generating LTP codes (during neighbor coparison, differences in threshold will be encoded as 0)
    use_image_mask: false   # if true, uses a mask of valid pixels for LTP (e.g. to avoid borders)

matching:
  metric: "hellinger"      # [chi2, cosine, hellinger]
  tolerance: 1     # tolerance for matching histograms. Matches will only be reported if distance is below this threshold. Set to 1 to allow all matches.
  top: 3          # Number of matches to report per image. Tolerance takes precedence.

# Processing to apply to image being matched against a set
query_image_processing:
  preprocessing:
    gaussian_blur: null
    gaussian_noise: null
    illumination: null
    contrast: null
    
  cropping:
    width: null
    height: null
    random_crop: false

# Processing to apply to images being matched against
# These values should be left null if wanting to test processed images against their raw counterparts 
target_image_processing:
  preprocessing:
    gaussian_blur: null
    gaussian_noise: null
    illumination: null
    contrast: null
    
  cropping:
    width: null
    height: null
    random_crop: false

data_engineering:
  histogram_smoothing: null

output:
  csv_filename: null
  pdf_filename: null
  visualize: true

logging:
  verbose: false